### ISSUE TITLE
Incompatible with django-querysetsequence==0.9

### ISSUE THREAD

**Issue by blueyed** [yourlabs/django-autocomplete-light#1050]
```
project/app/tests/test_autocomplete.py:42: in test_autocomplete_endpoints_access                                                                                                          
    response = p.callback(fake_request)                                                                                                                                                       
.venv/lib/python3.6/site-packages/django/views/generic/base.py:69: in view                                                                                                                    
    return self.dispatch(request, *args, **kwargs)                                                                                                                                            
project/app/dal.py:21: in dispatch                                                                                                                                                        
    return super().dispatch(request, *args, **kwargs)                                                                                                                                         
.venv/lib/python3.6/site-packages/dal/views.py:49: in dispatch                                                                                                                                
    return super(ViewMixin, self).dispatch(request, *args, **kwargs)                                                                                                                          
.venv/lib/python3.6/site-packages/django/views/generic/base.py:89: in dispatch                                                                                                                
    return handler(request, *args, **kwargs)                                                                                                                                                  
.venv/lib/python3.6/site-packages/django/views/generic/list.py:142: in get                                                                                                                    
    self.object_list = self.get_queryset()                                                                                                                                                    
project/app/dal.py:60: in get_queryset                                                                                                                                                    
    qs = self.mixup_querysets(qs)                                                                                                                                                             
.venv/lib/python3.6/site-packages/dal_queryset_sequence/views.py:34: in mixup_querysets                                                                                                       
    if len(list(qs.query._querysets)):                                                                                                                                                        
E   AttributeError: 'QuerySetSequence' object has no attribute 'query'                                                                                                                        
```

Bisected to https://github.com/percipient/django-querysetsequence/commit/ff622bf3b049cb9c7413e8604223f686ff6c019e.

Removed `.query` here: https://github.com/percipient/django-querysetsequence/commit/ff622bf3b049cb9c7413e8604223f686ff6c019e#diff-f45794d6f38e102567b2d30bce0797d7L478

**Comment by blueyed** [comment]
The code in our `dal.py` is:
```python
        qs = QuerySetSequence(qs1, qs2, …)
        qs = self.mixup_querysets(qs)
        return qs
```

So maybe not really a dal problem - need to investigate.

**Comment by littlehome-eugene** [comment]
I have the same problem with 3.2.10 (for django 1.11) and django-queryset 0.9, 0.10, 0.11.dev

**Comment by jpic** [comment]
django-queryset-sequence author gave a possible solution, anybody interested in contributing a PoC ?

https://github.com/percipient/django-querysetsequence/issues/21#issuecomment-432649275

**Comment by optiz0r** [comment]
PoC for the first usage of the private api in #1088. I have not yet found a way to resolve the second usage (in `mixup_querysets`).

**Comment by optiz0r** [comment]
Doing some more testing on #1088 last night I discovered a fatal flaw with using the indexed querysets approach. When rendering a bound form, which contains a `QuerySetSequence(Multiple)ModelField`, the initial value provided to the field is an unannotated object with no '#' attribute. This is to be expected, since it's not been sourced from a `QuerySetSequence` lookup. But it means there's no information available on which queryset index should be used to generate the `<option>` value. Under the present code, the ContentType is used to construct the ID string, so it's always derivable from the object.

Using the queryset index instead of the content type makes this a one-way operation. You can set the value on an empty form field, but you sanely cannot render a form field with a with an existing value or initial value.

This will either need to be done using the private api as implemented in #1056, or via a public api method on `QuerySetSequence` which does the same thing.
