### ISSUE TITLE
ImportError: cannot import name lru_cache

### ISSUE THREAD

**Issue by tderouin** [yourlabs/django-autocomplete-light#1102]
Python 2.7

Any ideas? My understanding is that the `lru_cache` decorator wasn't introduced until Python 3. 

```
(our-dev)[ec2-user@analytics our_site]$ ./manage.py shell_plus
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ec2-user/our-project/our_site/our_site/urls.py", line 25, in <module>
    from reports import views as reports_views
  File "/home/ec2-user/our-project/our_site/reports/views/__init__.py", line 2, in <module>
    from .views_maintenance import *
  File "/home/ec2-user/our-project/our_site/reports/views/views_maintenance.py", line 33, in <module>
    from .all import get_companies
  File "/home/ec2-user/our-project/our_site/reports/views/all.py", line 34, in <module>
    from dal import autocomplete
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/dal/autocomplete.py", line 38, in <module>
    from dal_select2.widgets import (
  File "/home/ec2-user/our-dev/local/lib/python2.7/dist-packages/dal_select2/widgets.py", line 3, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache
```

**Comment by jpic** [comment]
New DAL versions are not tested against Python 2, but compatibility pull request is accepted

**Comment by josircg** [comment]
I followed this instructions:

virtualenv autocomplete_light_env
source autocomplete_light_env/bin/activate
pip install -e git+git://github.com/yourlabs/django-autocomplete-light.git#egg=autocomplete_light
cd autocomplete_light_env/src/autocomplete-light/test_project
pip install -r requirements.txt
./manage.py runserver

How can I test with a previous version that it's working on python 2.7 ?

**Comment by jpic** [comment]
What do you mean not working ? lru_cache issue too ?

**Comment by josircg** [comment]
The master have this lru_cache issue.
stable/1.x.x got django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
dj111 has ImportError: No module named dal.test.utils

**Comment by jpic** [comment]
I wish I could help you, but i don't use Python 2 for years. Have ported all software I make / rely on to Python 3, contributed and forked where necessary.

However, pull requests for compatibility will be accepted.

**Comment by jpic** [comment]
Hi all of you **still looking for a Python 2 / Django 1.11 release**,

@ugkarthik is available for freelance work, if you want a python 2 release for dj1.1 it's time to say how much you're willing to pay for it and he'll tell you if its possible.

Please forward to whomever is your boss, i suppose a handfull of $100 contributions would work, we are able to make a proper bill from YourLabs Business Service France.

Please reply, I know you're a lot of users who would like a proper python 2 dj 1.11 release. If you've been using DAL in a project which is that old, it should mean that you made some profit out of it, so it shouldn't be such a hard sell to make a little effort to help a fellow hacker and have a good software package.

Have a great day

**Comment by josircg** [comment]
Hi folks, I was just trying to test it before add it to my project. 

The project that I'm working on is very small and I don't have budget to invest.
In fact, I didn't migrate to Python 3 for the same reason: I don't have the budget to upgrade the software.

Brazilian economy are really bad and it's hard to get some extra money for this kind of upgrade.
But if we find 4 other folks that want to invest, I can contribute with 20 euros.

**Comment by jpic** [comment]
This is really nice @josircg, thank you so much for your generous offer. I think it will be possible to package a python2/dj11 source code for a handful of 20 euro donations, in a manual and one-shot operation. After all, it only has to work for a year.

Try 3.2.10, it should work on python 2, otherwise this fork is the most recent that I have seen with dj11 support : https://github.com/mandarg/django-autocomplete-light/tree/dj111-update

For your Python 3 upgrade I'm sure you can do it, it's hard at the beginning, but after some practice you will learn porting code from 2 to 3 very well and very fast, then you will be able to upgrade anything you want for tiny time budget, it's a very useful skill.

Another option is [2to3](https://docs.python.org/2/library/2to3.html) can also automatically upgrade your code.

You know, we always have to upgrade our code one day or another. The more we wait: the more work it costs. 

I'm pretty silly when I did the move to Python 3 I was really feeling like I was already the last person and very late and now every other week there is a python 2 support request, I handled the transition pretty badly but at the same time it's really more work to support two versions

If you find a python 2 version that you like please let us know

Have a great day

**Comment by jpic** [comment]
Python 2 support in #1105 
Minor drawbacks but mostly work
Will merge and release when someone reports #1105 branch works fine on python 2
