### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [yourlabs/django-autocomplete-light#538]
AttributeError: module 'autocomplete_light' has no attribute 'AutocompleteModelTemplate'

This error occurred after I transfer from django 1.8 to 1.9

**Comment by blueyed** [comment]
Please provide more information, e.g. the traceback.

**Comment by Dean-Christian-Armada** [comment]
I an trying to convert my project from 1.8 to 1.9. So I did via pip install however when I tried to run python manage.py runserver the AttributeError responded
![selection_031](https://cloud.githubusercontent.com/assets/9837087/11806957/6a9a8918-a351-11e5-9a6a-48a9d7d9d85c.png)

**Comment by blueyed** [comment]
1) copy'n'pasting a traceback would be easier/better
2) it clearly happens in your ReferrerAutocomplete class; I don't know from the top of my head what might have changed here, but maybe something has moved / was deprecated before?!

**Comment by Dean-Christian-Armada** [comment]
Take note that this only happened in Django 1.9, it is working in Django 1.8 though


(python3.5-django1.9-people)adgc@mnl-adgc-pc1:~/Desktop/people$ python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f27880c80d0>
Traceback (most recent call last):
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/autocomplete_light/apps.py", line 9, in ready
    autodiscover()
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/autocomplete_light/registry.py", line 298, in autodiscover
    autodiscover_modules('autocomplete_light_registry')
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/adgc/.virtualenvs/python3.5-django1.9-people/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/adgc/Desktop/people/globals_declarations/autocomplete_light_registry.py", line 8, in <module>
    class ReferrerAutocomplete(autocomplete_light.AutocompleteModelTemplate):
AttributeError: module 'autocomplete_light' has no attribute 'AutocompleteModelTemplate'

**Comment by jpic** [comment]
https://github.com/yourlabs/django-autocomplete-light#projects-upgrading-to-django-19
