### ISSUE TITLE
Dal 3.10 not working with django 4.2

### ISSUE THREAD

**Issue by odooNextev** [yourlabs/django-autocomplete-light#1338]
Using latest version of Django and Dal, It retrieves me that error:
` AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'`

**Comment by jpic** [comment]
That's not in dal code
