### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'virtual_fields'

### ISSUE THREAD

**Issue by Guilouf** [yourlabs/django-autocomplete-light#973]
`django-autocomplete-light-3.2.10`

Django 2.0.1 and python 3.6.

Does not seems to be compatible with Django2 ?

Full trace: 
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/usr/local/lib/python3.6/dist-packages/dal/forms.py", line 152, in save
    self._save_m2m()
  File "/usr/local/lib/python3.6/dist-packages/dal/forms.py", line 126, in _save_m2m
    for f in chain(opts.many_to_many, opts.virtual_fields):
AttributeError: 'Options' object has no attribute 'virtual_fields'
[14/Feb/2018 15:28:14] "POST /gabarit/post_treatm
```ent HTTP/1.1" 500 97053

Happens when i submit a form, created from the generic foreign key tutorial.

**Comment by jpic** [comment]
Yep, does it work with django-autocomplete-light==3.3.0rc5 ?

**Comment by Guilouf** [comment]
Yep, it does work with this release
