### PR TITLE
[WIP] Switch to public api for retriving QSS querysets

### LINKED ISSUE #1050: Incompatible with django-querysetsequence==0.9
```
project/app/tests/test_autocomplete.py:42: in test_autocomplete_endpoints_access                                                                                                          
    response = p.callback(fake_request)                                                                                                                                                       
.venv/lib/python3.6/site-packages/django/views/generic/base.py:69: in view                                                                                                                    
    return self.dispatch(request, *args, **kwargs)                                                                                                                                            
project/app/dal.py:21: in dispatch                                                                                                                                                        
    return super().dispatch(request, *args, **kwargs)                                                                                                                                         
.venv/lib/python3.6/site-packages/dal/views.py:49: in dispatch                                                                                                                                
    return super(ViewMixin, self).dispatch(request, *args, **kwargs)                                                                                                                          
.venv/lib/python3.6/site-packages/django/views/generic/base.py:89: in dispatch                                                                                                                
    return handler(request, *args, **kwargs)                                                                                                                                                  
.venv/lib/python3.6/site-packages/django/views/generic/list.py:142: in get                                                                                                                    
    self.object_list = self.get_queryset()                                                                                                                                                    
project/app/dal.py:60: in get_queryset                                                                                                                                                    
    qs = self.mixup_querysets(qs)                                                                                                                                                             
.venv/lib/python3.6/site-packages/dal_queryset_sequence/views.py:34: in mixup_querysets                                                                                                       
    if len(list(qs.query._querysets)):                                                                                                                                                        
E   AttributeError: 'QuerySetSequence' object has no attribute 'query'                                                                                                                        
```

Bisected to https://github.com/percipient/django-querysetsequence/commit/ff622bf3b049cb9c7413e8604223f686ff6c019e.

Removed `.query` here: https://github.com/percipient/django-querysetsequence/commit/ff622bf3b049cb9c7413e8604223f686ff6c019e#diff-f45794d6f38e102567b2d30bce0797d7L478

### PR DESCRIPTION
**Pull request by optiz0r**
Switches from using an unsupported private API (which changed and broke
from django-querysetseqence>0.7) to a newly added public api method
(`get_querysets`) which achieves the same thing.

Depends on https://github.com/percipient/django-querysetsequence/pull/53
Supersedes #1056
Fixes #1050

### CODE REVIEW

**Comment by jpic** [comment]
Excellent work, passes tests for me ! Also nice upstream contribution, great testing and documentation, thank you very much pray :pray:

**Comment by optiz0r** [comment]
Upstream change is accepted and merged. Just waiting on a release before the [WIP] tag can be removed. For later reference, should be available in next QSS version after 0.10.

**Comment by jpic** [comment]
Grats for your contribution @optiz0r :+1: 

Keep up the good work and have a great day :tophat:

**Comment by optiz0r** [comment]
Thanks, although by merging this before QSS has published a new release, I think you have broken master branch?
